# Generated by Django 5.1.15 on 2026-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL for the contact page.', max_length=2000),
        ),
    ]
