# Generated by Django 5.1.15 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_companyprofile_google_maps_embed_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="about_image",
            field=models.ImageField(blank=True, null=True, upload_to="company/"),
        ),
    ]
