# Generated by Django 5.1.15 on 2026-09-20

from django.db import migrations, models


def create_initial_introduction_section(apps, schema_editor):
    CompanyProfile = apps.get_model("core", "CompanyProfile")
    HomeIntroductionSection = apps.get_model("core", "HomeIntroductionSection")

    if HomeIntroductionSection.objects.exists():
        return

    company = CompanyProfile.objects.filter(pk=1).first()
    if not company:
        return

    HomeIntroductionSection.objects.create(
        title="A dependable partner for businesses that value consistency.",
        description=(
            company.about_description
            or "K&K Trading Company brings together sourcing, logistics, and consultancy expertise "
            "to support partners who need dependable, on-time delivery and honest communication at every step."
        ),
        image=company.about_image.name if company.about_image else "",
        display_order=1,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_companyprofile_about_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeIntroductionSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="company/introduction/")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Homepage introduction section",
                "verbose_name_plural": "Homepage introduction sections",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.RunPython(create_initial_introduction_section, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="companyprofile",
            name="about_image",
        ),
    ]
